Migrate LaunchConfiguration to LaunchTemplate
widdix/aws-s3-virusscan pull request #95
Opened 2022-11-21 16:40 UTC by sgallen

**Motivation:**

The following message from AWS has prompted us to migrate from launch configurations to launch templates.

> Amazon EC2 Auto Scaling no longer adds support for new EC2 features to launch configurations and will stop supporting new EC2 instances types after December 31, 2022. We recommend that customers using launch configurations migrate to launch templates.

[Launch template documentation.](https://docs.aws.amazon.com/autoscaling/ec2/userguide/launch-templates.html)

**Solution:**

I've adjusted the CloudFormation template to leverage a launch template instead of a launch configuration. Through manual testing, the changes appear to be working as expected. I tested with and without a `SpotPrice` being specified.

2022-11-23 20:31 UTC, andreaswittig commented
@sgallen Thanks a lot for contributing to this project.

2022-11-23 20:34 UTC, andreaswittig requested changes

2022-11-23 20:34 UTC, andreaswittig commented on template.yaml
> +      LaunchTemplateName: ScanLaunchTemplate
We try to avoid fixed resources names to be able to create multiple stacks based on the same template. Do you agree with removing the `LaunchTemplateName` property?

2022-11-23 20:34 UTC, andreaswittig commented on template.yaml
> +        InstanceMarketOptions:
Please remove line break and fix indention.

2022-11-24 00:04 UTC, sgallen commented on template.yaml
> +      LaunchTemplateName: ScanLaunchTemplate
Happy to make that change. I didn't realize that it was optional but [I see that's the case](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html#aws-resource-ec2-launchtemplate-properties).

2022-11-24 00:21 UTC, sgallen commented on template.yaml
> +        InstanceMarketOptions:
Happy to change this to the style that you prefer. Unfortunately, I don't have much experience with CloudFormation templates so I'm not quite sure how to interpret your comment.

[Example 4 found in the AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-if) looks like the following: 

```
UpdatePolicy:
  AutoScalingRollingUpdate:
    !If 
      - RollingUpdates
      -
        MaxBatchSize: 2
        MinInstancesInService: 2
        PauseTime: PT0M30S
      - !Ref "AWS::NoValue"
```

Based on that it seems I should change it to:
```
InstanceMarketOptions:
  !If
    - HasSpotPrice
    - 
      MarketType: spot
      SpotOptions:
      MaxPrice: !Ref SpotPrice
    - !Ref AWS::NoValue
  ```

But I suspect that's not what you're looking for and also looks odd to me.

2022-11-28 16:35 UTC, sgallen commented on template.yaml
> +        InstanceMarketOptions:
@andreaswittig see above. As soon as I have your feedback I'll make the change. :+1:

2022-12-12 15:51 UTC, sgallen commented on template.yaml
> +        InstanceMarketOptions:
@andreaswittig sounds good :+1: I've made the requested change.

2022-12-14 07:34 UTC, andreaswittig commented
Thanks a lot, @sgallen!

2022-12-14 07:35 UTC, merged